// This file is autogenerated. Do not modify it directly.
import { ActionPanel, Action, Icon } from "@raycast/api";
import { showFailureToast } from "@raycast/utils";
import * as Boop from "~/scripts";

export default function Actions({ handleSubmit, onStart, onFailure, onSuccess }: ActionsProps) {
const onSubmit = (state: BoopState) => {
    try {
      onStart?.(state);
      Boop[state.intent](state);
      handleSubmit(state);
      onSuccess?.(state);
    } catch (error: unknown) {
      showFailureToast({ title: error instanceof Error ? error.message : String(error) });
      onFailure?.(state);
      return;
    }
  };

  return (
    <ActionPanel>
      <Action.SubmitForm
        title="JSON Minify"
        icon={Icon.CodeBlock}
        onSubmit={(state) => onSubmit({ ...state, intent: "jsonMinify" } as BoopState)}
      />
      <Action.SubmitForm
        title="JSON Pretty Print"
        icon={Icon.CodeBlock}
        onSubmit={(state) => onSubmit({ ...state, intent: "jsonPrettyPrint" } as BoopState)}
      />
      <Action.SubmitForm
        title="Lorem Ipsum Generator"
        icon={Icon.Document}
        onSubmit={(state) => onSubmit({ ...state, intent: "loremIpsum" } as BoopState)}
      />
      <Action.SubmitForm
        title="Base64 Decode"
        icon={Icon.LockUnlocked}
        onSubmit={(state) => onSubmit({ ...state, intent: "base64Decode" } as BoopState)}
      />
      <Action.SubmitForm
        title="Base64 Encode"
        icon={Icon.Lock}
        onSubmit={(state) => onSubmit({ ...state, intent: "base64Encode" } as BoopState)}
      />
      <Action.SubmitForm
        title="Camel Case"
        icon={Icon.TextCursor}
        onSubmit={(state) => onSubmit({ ...state, intent: "camelCase" } as BoopState)}
      />
      <Action.SubmitForm
        title="Generate Password"
        icon={Icon.Key}
        onSubmit={(state) => onSubmit({ ...state, intent: "generatePassword" } as BoopState)}
      />
      <Action.SubmitForm
        title="HTML Decode"
        icon={Icon.Code}
        onSubmit={(state) => onSubmit({ ...state, intent: "htmlDecode" } as BoopState)}
      />
      <Action.SubmitForm
        title="HTML Encode"
        icon={Icon.Code}
        onSubmit={(state) => onSubmit({ ...state, intent: "htmlEncode" } as BoopState)}
      />
      <Action.SubmitForm
        title="Kebab Case"
        icon={Icon.Minus}
        onSubmit={(state) => onSubmit({ ...state, intent: "kebabCase" } as BoopState)}
      />
      <Action.SubmitForm
        title="Lowercase"
        icon={Icon.TextCursor}
        onSubmit={(state) => onSubmit({ ...state, intent: "lowercase" } as BoopState)}
      />
      <Action.SubmitForm
        title="MD5 Hash"
        icon={Icon.Shield}
        onSubmit={(state) => onSubmit({ ...state, intent: "md5Hash" } as BoopState)}
      />
      <Action.SubmitForm
        title="Pascal Case"
        icon={Icon.TextCursor}
        onSubmit={(state) => onSubmit({ ...state, intent: "pascalCase" } as BoopState)}
      />
      <Action.SubmitForm
        title="Remove Duplicate Lines"
        icon={Icon.MinusCircle}
        onSubmit={(state) => onSubmit({ ...state, intent: "removeDuplicates" } as BoopState)}
      />
      <Action.SubmitForm
        title="Reverse Text"
        icon={Icon.ArrowLeftCircle}
        onSubmit={(state) => onSubmit({ ...state, intent: "reverseText" } as BoopState)}
      />
      <Action.SubmitForm
        title="SHA256 Hash"
        icon={Icon.Shield}
        onSubmit={(state) => onSubmit({ ...state, intent: "sha256Hash" } as BoopState)}
      />
      <Action.SubmitForm
        title="Snake Case"
        icon={Icon.Underline}
        onSubmit={(state) => onSubmit({ ...state, intent: "snakeCase" } as BoopState)}
      />
      <Action.SubmitForm
        title="Title Case"
        icon={Icon.TextCursor}
        onSubmit={(state) => onSubmit({ ...state, intent: "titleCase" } as BoopState)}
      />
      <Action.SubmitForm
        title="Trim Whitespaces"
        icon={Icon.TextCursor}
        onSubmit={(state) => onSubmit({ ...state, intent: "trimWhitespaces" } as BoopState)}
      />
      <Action.SubmitForm
        title="Uppercase"
        icon={Icon.TextCursor}
        onSubmit={(state) => onSubmit({ ...state, intent: "uppercase" } as BoopState)}
      />
      <Action.SubmitForm
        title="URL Decode"
        icon={Icon.Link}
        onSubmit={(state) => onSubmit({ ...state, intent: "urlDecode" } as BoopState)}
      />
      <Action.SubmitForm
        title="URL Encode"
        icon={Icon.Link}
        onSubmit={(state) => onSubmit({ ...state, intent: "urlEncode" } as BoopState)}
      />
    </ActionPanel>
  );
}
