// This file is autogenerated. Do not modify it directly.
import { ActionPanel, Action } from "@raycast/api";
import * as Boop from "~/scripts";

export default function Actions({ handleSubmit, onStart, onSuccess }: ActionsProps) {
  const onSubmit = (state: BoopState) => {
    onStart?.(state);
    Boop[state.intent](state);
    handleSubmit(state);
    onSuccess?.(state);
  };

  return (
    <ActionPanel>
            <Action.SubmitForm
        title="Base64 Encode"
        onSubmit={(state) => onSubmit({ ...state, intent: "base64Encode" } as BoopState)}
      />
      <Action.SubmitForm
        title="Trim Whitespaces"
        onSubmit={(state) => onSubmit({ ...state, intent: "trimWhitespaces" } as BoopState)}
      />
    </ActionPanel>
  );
}
